import pandas as pd

RACE_DATA_KUBUN_MAP = {
    "1": "entry",  # 出走馬名表(木曜)
    "2": "entryUpdated",  # 出馬表(金･土曜)
    "3": "resultsTop3Confirmed",  # 速報成績(3着まで確定)
    "4": "resultsTop5Confirmed",  # 速報成績(5着まで確定)
    "5": "resultsAllConfirmed",  # 速報成績(全馬着順確定)
    "6": "resultsAllWithCornerOrder",  # 速報成績(全馬着順+コーナ通過順)
    "7": "finalResults",  # 成績(月曜)
    "A": "regionalRace",  # 地方競馬
    "B": "internationalRace",  # 海外国際レース
    "9": "raceCanceled",  # レース中止
    "0": "recordDeleted",  # 該当レコード削除(提供ミスによる)
}


RACE_VENUE_CODE = pd.DataFrame(
    [
        ["00", "未設定", "", "", "", "", "unknown"],
        ["01", "札幌競馬場", "札", "札幌", "札幌", "SAPPORO", "central"],
        ["02", "函館競馬場", "函", "函館", "函館", "HAKODATE", "central"],
        ["03", "福島競馬場", "福", "福島", "福島", "FUKUSHIMA", "central"],
        ["04", "新潟競馬場", "新", "新潟", "新潟", "NIIGATA", "central"],
        ["05", "東京競馬場", "東", "東京", "東京", "TOKYO", "central"],
        ["06", "中山競馬場", "中", "中山", "中山", "NAKAYAMA", "central"],
        ["07", "中京競馬場", "名", "中京", "中京", "CHUKYO", "central"],
        ["08", "京都競馬場", "京", "京都", "京都", "KYOTO", "central"],
        ["09", "阪神競馬場", "阪", "阪神", "阪神", "HANSHIN", "central"],
        ["10", "小倉競馬場", "小", "小倉", "小倉", "KOKURA", "central"],
        ["30", "門別競馬場", "門", "門別", "門別", "MONBETSU", "regional"],
        ["31", "北見競馬場", "北", "北見", "北見", "KITAMI", "regional"],
        ["32", "岩見沢競馬場", "岩", "岩見", "岩見沢", "IWAMIZAWA", "regional"],
        ["33", "帯広競馬場", "帯", "帯広", "帯広", "OBIHIRO", "regional"],
        ["34", "旭川競馬場", "旭", "旭川", "旭川", "ASAHIKAWA", "regional"],
        ["35", "盛岡競馬場", "盛", "盛岡", "盛岡", "MORIOKA", "regional"],
        ["36", "水沢競馬場", "水", "水沢", "水沢", "MIZUSAWA", "regional"],
        ["37", "上山競馬場", "上", "上山", "上山", "KAMINOYAMA", "regional"],
        ["38", "三条競馬場", "三", "三条", "三条", "SANJYO", "regional"],
        ["39", "足利競馬場", "足", "足利", "足利", "ASHIKAGA", "regional"],
        ["40", "宇都宮競馬場", "宇", "宇都", "宇都宮", "UTSUNOMIYA", "regional"],
        ["41", "高崎競馬場", "高", "高崎", "高崎", "TAKASAKI", "regional"],
        ["42", "浦和競馬場", "浦", "浦和", "浦和", "URAWA", "regional"],
        ["43", "船橋競馬場", "船", "船橋", "船橋", "FUNABASHI", "regional"],
        ["44", "大井競馬場", "大", "大井", "大井", "OHI", "regional"],
        ["45", "川崎競馬場", "川", "川崎", "川崎", "KAWASAKI", "regional"],
        ["46", "金沢競馬場", "金", "金沢", "金沢", "KANAZAWA", "regional"],
        ["47", "笠松競馬場", "笠", "笠松", "笠松", "KASAMATSU", "regional"],
        ["48", "名古屋競馬場", "古", "名古", "名古屋", "NAGOYA", "regional"],
        ["49", "紀三井寺競馬場", "紀", "紀三", "紀三寺", "KIMIIDERA", "regional"],
        ["50", "園田競馬場", "園", "園田", "園田", "SONODA", "regional"],
        ["51", "姫路競馬場", "姫", "姫路", "姫路", "HIMEJI", "regional"],
        ["52", "益田競馬場", "益", "益田", "益田", "MASUDA", "regional"],
        ["53", "福山競馬場", "福", "福山", "福山", "FUKUYAMA", "regional"],
        ["54", "高知競馬場", "高", "高知", "高知", "KOCHI", "regional"],
        ["55", "佐賀競馬場", "佐", "佐賀", "佐賀", "SAGA", "regional"],
        ["56", "荒尾競馬場", "荒", "荒尾", "荒尾", "ARAO", "regional"],
        ["57", "中津競馬場", "中", "中津", "中津", "NAKATSU", "regional"],
        ["58", "札幌競馬場（地方競馬）", "札", "札幌", "札幌", "SAPPORO(NAR)", "regional"],
        ["59", "函館競馬場（地方競馬）", "函", "函館", "函館", "HAKODATE(NAR)", "regional"],
        ["60", "新潟競馬場（地方競馬）", "新", "新潟", "新潟", "NIIGATA(NAR)", "regional"],
        ["61", "中京競馬場（地方競馬）", "名", "中京", "中京", "CHUKYO(NAR)", "regional"],
        ["A0", "その他の外国", "外", "他外", "他外国", "OTHER", "international"],
        ["A2", "日本", "日", "日本", "日本", "Japan JPN", "international"],
        [
            "A4",
            "アメリカ",
            "米",
            "アメ",
            "アメリ",
            "United States of America USA",
            "international",
        ],
        ["A6", "イギリス", "英", "イギ", "イギリ", "Great Britain GB", "international"],
        ["A8", "フランス", "仏", "フラ", "フラン", "France FR", "international"],
        ["B0", "インド", "印", "イン", "インド", "India IND", "international"],
        ["B2", "アイルランド", "愛", "アイ", "アイル", "Ireland IRE", "international"],
        ["B4", "ニュージーランド", "新", "ニュ", "ニュー", "New Zealand NZ", "international"],
        ["B6", "オーストラリア", "豪", "オー", "オース", "Australia AUS", "international"],
        ["B8", "カナダ", "加", "カナ", "カナダ", "Canada CAN", "international"],
        ["C0", "イタリア", "伊", "イタ", "イタリ", "Italy ITY", "international"],
        ["C2", "ドイツ", "独", "ドイ", "ドイツ", "Germany GER", "international"],
        ["C4", "(未使用)", "", "", "", "", "unknown"],
        ["C5", "オマーン", "オ", "オマ", "オマー", "Oman OMN", "international"],
        ["C6", "イラク", "イ", "イラ", "イラク", "Iraq IRQ", "international"],
        [
            "C7",
            "アラブ首長国連邦",
            "首",
            "(ア)",
            "ア首",
            "アラブ United Arab Emirates UAE",
            "international",
        ],
        ["C8", "シリア", "叙", "シリ", "シリア", "Syrian SYR", "international"],
        ["D0", "スウェーデン", "瑞", "スウ", "スウェ", "Sweden SWE", "international"],
        ["D2", "ハンガリー", "洪", "ハン", "ハンガ", "Hungary HUN", "international"],
        ["D4", "ポルトガル", "葡", "ポル", "ポルト", "Portugal POR", "international"],
        ["D6", "ロシア", "露", "ロシ", "ロシア", "Russia RUS", "international"],
        ["D8", "ウルグアイ", "宇", "ウル", "ウルグ", "Uruguay URU", "international"],
        ["E0", "ペルー", "秘", "ペル", "ペルー", "Peru PER", "international"],
        ["E2", "アルゼンチン", "亜", "アル", "アルゼ", "Argentina ARG", "international"],
        ["E4", "ブラジル", "伯", "ブラ", "ブラジ", "Brazil BRZ", "international"],
        ["E6", "ベルギー", "白", "ベル", "ベルギ", "Belgium BEL", "international"],
        ["E8", "トルコ", "土", "トル", "トルコ", "Turkey TUR", "international"],
        ["F0", "韓国", "韓", "韓国", "韓国", "Korea KOR", "international"],
        ["F1", "中国", "中", "中国", "中国", "China CHN", "international"],
        ["F2", "チリ", "智", "チリ", "チリ", "Chile CHI", "international"],
        ["F4", "(未使用)", "", "", "", "", "unknown"],
        ["F6", "(未使用)", "", "", "", "", "unknown"],
        ["F8", "パナマ", "巴", "パナ", "パナマ", "Panama PAN", "international"],
        ["G0", "香港", "香", "香港", "香港", "Hong Kong HK", "international"],
        ["G2", "スペイン", "西", "スペ", "スペイ", "Spain SPA", "international"],
        ["G4", "(未使用)", "", "", "", "", "unknown"],
        ["G6", "(未使用)", "", "", "", "", "unknown"],
        ["G8", "(未使用)", "", "", "", "", "unknown"],
        ["H0", "西ドイツ", "独", "西独", "西独", "West Germany GER", "international"],
        ["H2", "南アフリカ", "南", "(阿)", "南ア", "South Africa SAF", "international"],
        ["H4", "スイス", "ス", "スイ", "スイス", "Switzerland SWI", "international"],
        ["H6", "モナコ", "モ", "モナ", "モナコ", "Monaco MCO", "international"],
        ["H8", "フィリピン", "比", "フィ", "フィリ", "Philippines PHI", "international"],
        ["I0", "プエルトリコ", "プ", "プエ", "プエル", "Puerto Rico PUE", "international"],
        ["I2", "コロンビア", "コ", "コロ", "コロン", "Colombia COL", "international"],
        ["I4", "チェコスロバキア", "チ", "チェ", "チェコ", "Czechoslovakia CZE", "international"],
        ["I6", "チェコ", "チ", "チェ", "チェコ", "Czech Republic CZE", "international"],
        ["I8", "スロバキア", "ス", "スロ", "スロバ", "Slovakia SLO", "international"],
        ["J0", "エクアドル", "エ", "エク", "エクア", "Ecuador ECU", "international"],
        ["J2", "ギリシャ", "ギ", "ギリ", "ギリシ", "Greece GR", "international"],
        ["J4", "マレーシア", "馬", "マレ", "マレー", "Malaysia MAL", "international"],
        ["J6", "メキシコ", "墨", "メキ", "メキシ", "Mexico MEX", "international"],
        ["J8", "モロッコ", "摩", "モロ", "モロッ", "Morocco MOR", "international"],
        ["K0", "パキスタン", "基", "パキ", "パキス", "Pakistan PAK", "international"],
        ["K2", "ポーランド", "波", "ポー", "ポーラ", "Poland POL", "international"],
        ["K4", "パラグアイ", "拉", "パラ", "パラグ", "Paraguay PRY", "international"],
        ["K6", "サウジアラビア", "サ", "サウ", "サウジ", "Saudi Arabia SDA", "international"],
        ["K8", "キプロス", "キ", "キプ", "キプロ", "Cyprus CYP", "international"],
        ["L0", "タイ", "泰", "タイ", "タイ", "Thailand THA", "international"],
        ["L2", "ウクライナ", "烏", "ウク", "ウクラ", "Ukraine UKR", "international"],
        ["L4", "ベネズエラ", "ベ", "ベネ", "ベネゼ", "Venezuela VEN", "international"],
        ["L6", "ユーゴスラビア", "ユ", "ユー", "ユーゴ", "Yugoslavia YUG", "international"],
        ["L8", "デンマーク", "丁", "デン", "デンマ", "Denmark DEN", "international"],
        ["M0", "シンガポール", "嘉", "シン", "シンガ", "Singapore SIN", "international"],
        ["M2", "マカオ", "澳", "澳門", "マカオ", "Macau MAC", "international"],
        ["M4", "オーストリア", "墺", "墺", "墺国", "Austria AUT", "international"],
        ["M6", "ヨルダン", "約", "約", "ヨルダ", "Jordan JOR", "international"],
        ["M8", "カタール", "華", "華", "カタル", "Qatar QAT", "international"],
        ["N0", "東ドイツ", "独", "東独", "東独", "East Germany GER", "international"],
        ["N2", "バーレーン", "巴", "巴林", "バーレ", "Bahrain BHR", "international"],
    ],
    columns=["code", "nameJP", "short1", "short2", "short3", "nameEN", "venueType"],
)

DAY_OF_WEEK_CODE = pd.DataFrame(
    [
        [0, "未設定", "", "", "", "", ""],
        [1, "土曜日", "土", "土曜", "土曜日", "SATURDAY", "SAT"],
        [2, "日曜日", "日", "日曜", "日曜日", "SUNDAY", "SUN"],
        [3, "祝日", "祝", "祝日", "祝日", "NATIONAL HOLIDAY", "HOL"],
        [4, "月曜日", "月", "月曜", "月曜日", "MONDAY", "MON"],
        [5, "火曜日", "火", "火曜", "火曜日", "TUESDAY", "TUE"],
        [6, "水曜日", "水", "水曜", "水曜日", "WEDNESDAY", "WED"],
        [7, "木曜日", "木", "木曜", "木曜日", "THURSDAY", "THU"],
        [8, "金曜日", "金", "金曜", "金曜日", "FRIDAY", "FRI"],
    ],
    columns=["code", "nameJP", "short1", "short2", "nameLongJP", "nameEN", "shortEN"],
)

RACE_TYPE_CODE = pd.DataFrame(
    [
        ["00", "未設定", "", "", "", ""],
        ["11", "サラブレッド系2歳", "サラ２才", "サラ系２歳", "サラ系２歳", "TWO-YEAR-OLDS"],
        ["12", "サラブレッド系3歳", "サラ３才", "サラ系３歳", "サラ系３歳", "THREE-YEAR-OLDS"],
        ["13", "サラブレッド系3歳以上", "サラ３上", "サラ系３歳上", "サラ系３歳以上", "THREE-YEAR-OLDS & UP"],
        ["14", "サラブレッド系4歳以上", "サラ４上", "サラ系４歳上", "サラ系４歳以上", "FOUR-YEAR-OLDS & UP"],
        [
            "18",
            "サラブレッド系障害3歳以上",
            "障害３上",
            "障害３歳上",
            "サラ障害３歳以上",
            "THREE-YEAR-OLDS & UP STEEPLE-CHASE",
        ],
        [
            "19",
            "サラブレッド系障害4歳以上",
            "障害４上",
            "障害４歳上",
            "サラ障害４歳以上",
            "FOUR-YEAR-OLDS & UP STEEPLE-CHASE",
        ],
        ["21", "アラブ系2歳", "アラ２才", "アラ系２歳", "アラブ系２歳", "TWO-YEAR-OLDS ANGLO-ARABS"],
        ["22", "アラブ系3歳", "アラ３才", "アラ系３歳", "アラブ系３歳", "THREE-YEAR-OLDS ANGLO-ARABS"],
        [
            "23",
            "アラブ系3歳以上",
            "アラ３上",
            "アラ系３歳上",
            "アラブ系３歳以上",
            "THREE-YEAR-OLDS & UP ANGLO-ARABS",
        ],
        [
            "24",
            "アラブ系4歳以上",
            "アラ４上",
            "アラ系４歳上",
            "アラブ系４歳以上",
            "FOUR-YEAR-OLDS & UP ANGLO-ARABS",
        ],
    ],
    columns=["code", "nameJP", "short4c", "short6c", "short8c", "nameEN"],
)
